/**
 * @fileoverview Island mount function for client-side hydration.
 *
 * This file runs exclusively in the browser. It is bundled by `sprout-build`
 * or `sprout-dev` and loaded by the island wrapper generated by
 * {@link generateIslandWrapper}.
 *
 * ## Rendering model
 *
 * Uses a full `innerHTML` replacement strategy. Hono's JSX runtime is
 * string-serialisation-first, so islands are rendered to an HTML string
 * and injected via `el.innerHTML`. Signal-driven incremental updates
 * require manual DOM manipulation via {@link useEffect}.
 */

import type { FC } from "@hono/hono/jsx";
import {
  getIslandName,
  HydrationError,
  IslandErrorEvent,
  RenderError,
  renderToString,
  validateProps,
} from "./stringify.ts";

/**
 * Dispatches an `island-error` event on `el` if it supports `dispatchEvent`.
 * Guards against plain object mocks used in tests.
 */
function dispatchIslandError(
  el: Element,
  island: string,
  error: Error,
): void {
  if (typeof el.dispatchEvent === "function") {
    el.dispatchEvent(new IslandErrorEvent({ error, island }));
  }
}

/**
 * Render a JSX island component into a DOM element using innerHTML.
 *
 * ## Rendering model (0.1.0)
 *
 * Hono's JSX runtime is string-serialisation-first - it has no DOM reconciler.
 * For 0.1.0, island hydration therefore uses a **full innerHTML replacement**:
 *   1. Call `Component(props)` to get a JSX node.
 *   2. Serialise to an HTML string via `renderToString`.
 *   3. Set `el.innerHTML` once.
 *
 * Signal-driven incremental DOM updates are **not automatic** in 0.1.0.
 * Island components that need reactivity must manage DOM mutations directly via
 * `useEffect` + `el.querySelector(…).textContent = …` or equivalent imperative
 * DOM calls. A real incremental renderer is a Phase 5 item.
 *
 * ## Error handling
 *
 * Hydration errors are dispatched as bubbling `CustomEvent("island-error")`
 * on the island element so the host application can observe failures. Errors
 * are not thrown to avoid crashing the broader page.
 *
 * @param Component  The island's JSX functional component.
 * @param props      Deserialised props from the `data-props` attribute.
 * @param el         The container element (`[data-island]` div).
 * @returns A dispose function. Currently a no-op, reserved for future
 *          cleanup of effects registered by the component.
 */
export function mount<P extends Record<string, unknown>>(
  Component: FC<P>,
  props: P,
  el: Element,
): () => void {
  if (!validateProps(props)) {
    const err = new HydrationError("Invalid props: expected a non-null object");
    dispatchIslandError(el, getIslandName(el), err);
    return () => { };
  }
  try {
    const html = renderToString(Component(props));
    el.innerHTML = html;
  } catch (err) {
    const error = err instanceof RenderError
      ? new HydrationError(`[sprout] Render error: ${err.message}`, err.reason)
      : new HydrationError(
        `[sprout] Failed to hydrate island: ${err instanceof Error ? err.message : String(err)
        }`,
        err,
      );
    dispatchIslandError(el, getIslandName(el), error);
  }
  return () => { }; // TODO(v0.2.0): implement real dispose with effect cleanup
}
