/**
 * @fileoverview Island mount function for client-side hydration.
 *
 * This file runs exclusively in the browser. It is bundled by `sprout-build`
 * or `sprout-dev` and loaded by the island wrapper generated by
 * {@link generateIslandWrapper}.
 *
 * ## Rendering model
 *
 * Uses a full `innerHTML` replacement strategy. Hono's JSX runtime is
 * string-serialisation-first, so islands are rendered to an HTML string
 * and injected via `el.innerHTML`. Signal-driven incremental updates
 * require manual DOM manipulation via {@link useEffect}.
 */

/// <reference lib="dom" />
import { renderToString } from "@hono/hono/jsx/dom/server";
import type { FC } from "@hono/hono/jsx";
import { validateProps } from "./props.ts";

/**
 * Error thrown when island hydration fails.
 */
export class HydrationError extends Error {
  constructor(
    message: string,
    public reason?: unknown,
  ) {
    super(message);
    this.name = "HydrationError";
  }
}

/**
 * Detail payload for the `island-error` CustomEvent.
 *
 * @example
 * ```ts
 * document.addEventListener("island-error", (e: IslandErrorEvent) => {
 *   console.error(e.detail.island, e.detail.error.message);
 * });
 * ```
 */
export interface IslandErrorDetail {
  /** The error that caused the hydration failure. */
  error: Error;
  /** The island name, or `"unknown"` if the name could not be determined. */
  island: string;
}

/**
 * Typed custom event dispatched on an island element when hydration fails.
 * Extends `CustomEvent` with the {@link IslandErrorDetail} detail type.
 */
export class IslandErrorEvent extends CustomEvent<IslandErrorDetail> {
  constructor(detail: IslandErrorDetail) {
    super("island-error", { detail, bubbles: true });
  }
}

/**
 * Dispatches an `island-error` event on `el` if it supports `dispatchEvent`.
 * Guards against plain object mocks used in tests.
 */
function dispatchIslandError(
  el: Element,
  island: string,
  error: Error,
): void {
  if (typeof el.dispatchEvent === "function") {
    el.dispatchEvent(new IslandErrorEvent({ error, island }));
  }
}

/**
 * Safely extracts the island name from an element for error reporting.
 * Returns `"unknown"` when the attribute is unavailable or absent.
 * Guards against plain object mocks used in tests.
 */
function getIslandName(el: Element): string {
  if (typeof el.getAttribute !== "function") return "unknown";
  return el.getAttribute("data-island") ?? "unknown";
}

/**
 * Render a JSX island component into a DOM element using innerHTML.
 *
 * ## Rendering model (0.1.0)
 *
 * Hono's JSX runtime is string-serialisation-first - it has no DOM reconciler.
 * For 0.1.0, island hydration therefore uses a **full innerHTML replacement**:
 *   1. Call `Component(props)` to get a JSX node.
 *   2. Serialise to an HTML string via `renderToString`.
 *   3. Set `el.innerHTML` once.
 *
 * Signal-driven incremental DOM updates are **not automatic** in 0.1.0.
 * Island components that need reactivity must manage DOM mutations directly via
 * `useEffect` + `el.querySelector(…).textContent = …` or equivalent imperative
 * DOM calls. A real incremental renderer is a Phase 5 item.
 *
 * ## Error handling
 *
 * Hydration errors are dispatched as bubbling `CustomEvent("island-error")`
 * on the island element so the host application can observe failures. Errors
 * are not thrown to avoid crashing the broader page.
 *
 * @param Component  The island's JSX functional component.
 * @param props      Deserialised props from the `data-props` attribute.
 * @param el         The container element (`[data-island]` div).
 * @returns A dispose function. Currently a no-op; reserved for future
 *          cleanup of effects registered by the component.
 */
export async function mount<P extends Record<string, unknown>>(
  Component: FC<P>,
  props: P,
  el: Element,
): Promise<() => void> {
  if (!validateProps(props)) {
    const err = new HydrationError("Invalid props: expected a non-null object");
    dispatchIslandError(el, getIslandName(el), err);
    return () => {};
  }
  try {
    const html = await renderToString(Component(props));
    el.innerHTML = html;
  } catch (err) {
    const error = new HydrationError(
      `[sprout] Failed to hydrate island: ${
        err instanceof Error ? err.message : String(err)
      }`,
      err,
    );
    dispatchIslandError(el, getIslandName(el), error);
  }
  return () => {}; // TODO(v0.2.0): implement real dispose with effect cleanup
}
