/**
 * @fileoverview Island mount function for client-side hydration.
 *
 * This file runs exclusively in the browser. It is bundled by `sprout-build`
 * or `sprout-dev` and loaded by the island wrapper generated by
 * {@link generateIslandWrapper}.
 *
 * ## Rendering model
 *
 * Uses a full `innerHTML` replacement strategy. Hono's JSX runtime is
 * string-serialisation-first, so islands are rendered to an HTML string
 * and injected via `el.innerHTML`. Signal-driven incremental updates
 * require manual DOM manipulation via {@link useEffect}.
 */

import type { FC } from "@hono/hono/jsx";
import {
  getIslandName,
  HydrationError,
  IslandErrorEvent,
  RenderError,
  renderToString,
  validateProps,
} from "./stringify.ts";

/**
 * Dispatches an `island-error` event on `el` if it supports `dispatchEvent`.
 * Guards against plain object mocks used in tests.
 */
function dispatchIslandError(
  el: Element,
  island: string,
  error: Error,
): void {
  if (typeof el.dispatchEvent === "function") {
    el.dispatchEvent(new IslandErrorEvent({ error, island }));
  }
}

/**
 * Map from HTML attribute name (e.g. "onclick") to event name (e.g. "click").
 * Only those attributes that bind to event listeners are included.
 */
const EVENT_ATTR_MAP: Record<string, string> = {
  onclick: "click",
  onchange: "change",
  oninput: "input",
  onblur: "blur",
  onfocus: "focus",
  onkeydown: "keydown",
  onkeyup: "keyup",
  onkeypress: "keypress",
  onmouseenter: "mouseenter",
  onmouseleave: "mouseleave",
  onmouseover: "mouseover",
  onmouseout: "mouseout",
  ondblclick: "dblclick",
  onfocusout: "focusout",
  onload: "load",
  onerror: "error",
  onsubmit: "submit",
};

/**
 * Re-attach event handlers to elements that were set via innerHTML.
 *
 * Hono's JSX string renderer drops all function-valued props (including
 * event handlers like `onClick={handleClick}`) during HTML serialisation.
 * innerHTML parsing therefore creates DOM nodes with no event listeners.
 *
 * This function parses the rendered HTML, walks the DOM tree, and uses
 * the original props object to restore event listeners by matching
 * handler prop names to their corresponding HTML attributes.
 *
 * Note: only works for handlers stored as direct prop values. Inline arrow
 * functions in JSX (e.g. `onClick={() => doSomething()}`) cannot be restored
 * this way since the function object is not preserved in props. The long-term
 * fix is a real DOM reconciler.
 *
 * @param el    - The container element
 * @param props - The props passed to the island component
 */
function attachEventHandlers(
  el: Element,
  props: Record<string, unknown>,
): void {
  // Build a map of HTML attribute name → prop key for any function-valued props
  // that correspond to known event handler names (e.g. onClick → handleClick)
  const eventAttrToHandlerKey = new Map<string, string>();
  for (const key of Object.keys(props)) {
    const lower = key.toLowerCase();
    if (lower in EVENT_ATTR_MAP && typeof props[key] === "function") {
      eventAttrToHandlerKey.set(lower, key);
    }
  }

  if (eventAttrToHandlerKey.size === 0) return;

  // Walk el's already-parsed children and attach handlers to matching elements
  const allEls = el.querySelectorAll("*");
  for (const el2 of allEls) {
    for (const [htmlAttr, handlerKey] of eventAttrToHandlerKey) {
      const attrValue = el2.getAttribute(htmlAttr);
      if (!attrValue) continue;
      const handler = props[handlerKey];
      if (typeof handler === "function") {
        el2.addEventListener(
          EVENT_ATTR_MAP[htmlAttr],
          handler as EventListener,
        );
      }
    }
  }
}

/**
 * Render a JSX island component into a DOM element using innerHTML.
 *
 * ## Rendering model (0.1.0)
 *
 * Hono's JSX runtime is string-serialisation-first - it has no DOM reconciler.
 * For 0.1.0, island hydration therefore uses a **full innerHTML replacement**:
 *   1. Call `Component(props)` to get a JSX node.
 *   2. Serialise to an HTML string via `renderToString` (async).
 *   3. Set `el.innerHTML` once.
 *   4. Re-attach event handlers by parsing the HTML and matching props.
 *
 * Signal-driven incremental DOM updates are **not automatic** in 0.1.0.
 * Island components that need reactivity must manage DOM mutations directly via
 * `useEffect` + `el.querySelector(…).textContent = …` or equivalent imperative
 * DOM calls. A real incremental renderer is a Phase 5 item.
 *
 * ## Error handling
 *
 * Hydration errors are dispatched as bubbling `CustomEvent("island-error")`
 * on the island element so the host application can observe failures. Errors
 * are not thrown to avoid crashing the broader page.
 *
 * @param Component  The island's JSX functional component.
 * @param props      Deserialised props from the `data-props` attribute.
 * @param el         The container element (`[data-island]` div).
 * @returns A dispose function. Currently a no-op, reserved for future
 *          cleanup of effects registered by the component.
 */
export async function mount<P extends Record<string, unknown>>(
  Component: FC<P>,
  props: P,
  el: Element,
): Promise<() => void> {
  if (!validateProps(props)) {
    const err = new HydrationError("Invalid props: expected a non-null object");
    dispatchIslandError(el, getIslandName(el), err);
    return () => {};
  }
  try {
    const html = await renderToString(Component(props));
    el.innerHTML = html;
    // Re-attach event handlers after innerHTML is set
    attachEventHandlers(el, props as Record<string, unknown>);
  } catch (err) {
    const error = err instanceof RenderError
      ? new HydrationError(`[sprout] Render error: ${err.message}`, err.reason)
      : new HydrationError(
        `[sprout] Failed to hydrate island: ${
          err instanceof Error ? err.message : String(err)
        }`,
        err,
      );
    dispatchIslandError(el, getIslandName(el), error);
  }
  return () => {}; // TODO(v0.2.0): implement real dispose with effect cleanup
}
